version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "10:17"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 5
    labels: [dependencies, security-review-required]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "10:37"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 5
    labels: [dependencies, security-review-required]
